### ISSUE TITLE
Truncating trailing 0

### ISSUE THREAD

**Issue by sreed-crow** [codeandcats/reliable-round#423]
This package is working great except for when a value rounds to a whole number. In those cases the trailing 0s are truncated. For example, 19.02417696 rounded to a a single decimal place (round(x, 1)), returns 19, when we would like it to return 19.0.

**Comment by codeandcats** [comment]
Hi @sreed-crow. The `round` function returns a `number` type, thus there is no difference between `19` and `19.0`. If you would like to *display* it with decimals you will want to convert it to a string. See [Number.prototype.toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed)

A side note: I wrote `reliable-round` for a very specific use case which needed absolute accuracy, but honestly it's not necessary in most use cases. If you all you need to do is round a number and have the answer right 99.99%+ of the time, then `Math.round` will likely be sufficient. For example, if you need to round to 2 decimal places you can just do: `Math.round(x * 100) / 100`. Hope this helps.
